language: c
dist: trusty
sudo: false
matrix:
    include:
        - compiler: gcc
        - compiler: clang
        - compiler: gcc-5
        - compiler: clang-3.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
        packages:
            - gcc-5
            - clang-3.8
script:
    - ${CC} --version
    - env
